a:5:{i:0;s:219:"Error in file: "D:\xampp\htdocs\qsoftvn_ept537\app\code\local\Webkul\Marketplace\sql\marketplace_setup\mysql4-upgrade-1.0.1-1.0.2.php" - SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'order_item_id'";i:1;s:1010:"#0 D:\xampp\htdocs\qsoftvn_ept537\app\code\core\Mage\Core\Model\Resource\Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 D:\xampp\htdocs\qsoftvn_ept537\app\code\core\Mage\Core\Model\Resource\Setup.php(437): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '1.0.1', '1.0.2')
#2 D:\xampp\htdocs\qsoftvn_ept537\app\code\core\Mage\Core\Model\Resource\Setup.php(320): Mage_Core_Model_Resource_Setup->_upgradeResourceDb('1.0.1', '1.0.2')
#3 D:\xampp\htdocs\qsoftvn_ept537\app\code\core\Mage\Core\Model\Resource\Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 D:\xampp\htdocs\qsoftvn_ept537\app\code\core\Mage\Core\Model\App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 D:\xampp\htdocs\qsoftvn_ept537\app\code\core\Mage\Core\Model\App.php(343): Mage_Core_Model_App->_initModules()
#6 D:\xampp\htdocs\qsoftvn_ept537\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#7 D:\xampp\htdocs\qsoftvn_ept537\index.php(87): Mage::run('', 'store')
#8 {main}";s:3:"url";s:111:"/qsoftvn_ept537/index.php/admin/system_config/edit/section/porto_settings/key/278fe5c57ca9d7e8c75db0d4b6c6d067/";s:11:"script_name";s:25:"/qsoftvn_ept537/index.php";s:4:"skin";s:7:"default";}